### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by yallop** [hannesm/hannes.nqsb.io#1]
At the moment there doesn't appear to be a feed.  It'd be useful to have a way of making your posts turn up in a news reader.

**Comment by hannesm** [comment]
we should ask @Engil  to implement RSS in Canopy :)

**Comment by hannesm** [comment]
since I won't fix it here, I moved this issue over to his canopy project

**Comment by hannesm** [comment]
btw now available at https://hannes.nqsb.io/atom
