### ISSUE TITLE
Und gleich mit der Tür ins Haus

### ISSUE THREAD

**Issue by benkb** [hannesm/hannes.nqsb.io#11]
Hallo Hannes
Schon seit längerer Zeit wollte ich mal in Kontakt zu Dir treten. Ist dies hier der richtige Kanal und/oder machst Du auch email? 

Es geht um ein Projekt (codename "tell"), dass mir schon (zu) lange auf dem Herzen liegt und Unikernel und weitere Dir bekannte Technologien beinhaltet. Da ich ziemlich viele Ideen habe möchte ich Dich hier von meiner "Vision" verschonen sondern mal von einem ersten Schritt sprechen. Dieser besteht aus einem Dienst, der es usern ermöglicht, über eine Weboberfläche unikernels zu erstellen und verwalten.

Alle meine versuche das selber umzusetzen sind schon von Beginn weg gescheitert, ich habe dann vor ca. einem Jahr auch mal noch ein Startup (tarides) kontaktiert das genau diese Technologien abdeckt. Das hat mich aber auch nicht weitergebracht und ich hab die Sache beerdigt. 

Nun bin ich heute über einen Artikel von Dir gestossen, der das deployment tool 'Albatros` beschreibt, ausserdem habe ich auch Deine mitarbeit am caldav server eingesehen. Beides hat mich stark beeindruckt, was mich bewogen hat nochmals einen Versuch zu starten ...

Gerne würde ich die Möglichkeiten besprechen, wie eine allfaellige Zusammenarbeit aussehen könnte. Allerdings habe ich ja keine Ahnung ob Du überhaupt an diesem Dialog interessiert bist und wies bei Dir zeitlich aussieht.

Was die Finanzen angeht, so ist meine Überlegung, dass ich einen Teil selber finanziere und dann aber auch versuche privates und öffentliches Geld aufzutreiben.

Meld Dich doch mal!
Lieber Gruss
Ben

**Comment by benkb** [comment]
Huch, das ist ja alles öffentlich ....

**Comment by hannesm** [comment]
am besten per mail -> hannes@mehnert.org (dieser issue tracker hier ist oeffentlich)
